import sys
import subprocess

# Rubik's cube 2x2 is define by 6 faces/colors (up:1, front:2, left:3, back:4, right:5, down:6)
#     with on each face, 4 facelets (up-left:1, up-right:2, down-left:3, down-right:4).
#
#         |0|1|
#         |2|3|
#     |0|1|0|1|0|1|0|1|
#     |2|3|2|3|2|3|2|3|
#         |0|1|
#         |2|3|


#input : a file name
#output : Rubik's cube representation
def read_file(filename):
    myfile = open(filename, 'r')
    rubiks = [[0 for i in range(4)] for j in range(6)]
    i = 0
    j = 0
    it = 0
    for line in myfile:
        for element in line:
            if it<24:
                it = it+1
                rubiks[i][j] = int(element)
                if int(element) > 5:
                    exit('number ' + str(element) + ' does not correspond to a color')
                j = (j+1)%4
                if j==0:
                    i = i+1
            else:
                return rubiks
    if it == 24:
        return rubiks
    exit('not enough characters (need 24 but only '+ str(it) + ')\n')

#input: -myfile: name of the file where to write the chain
#       -rubiks: Rubik's cube to write 
def print_rubiks(myfile, rubiks):
    myfile.write("    |"+ str(rubiks[0][0])+"|"+str(rubiks[0][1])+"|\n")
    myfile.write("    |"+ str(rubiks[0][2])+"|"+str(rubiks[0][3])+"|\n")
    myfile.write("|"+str(rubiks[2][0])+"|"+str(rubiks[2][1])+"|"+ str(rubiks[1][0])+"|"+str(rubiks[1][1])+"|"+str(rubiks[4][0])+"|"+str(rubiks[4][1])+"|"+str(rubiks[3][0])+"|"+str(rubiks[3][1])+"|\n")
    myfile.write("|"+str(rubiks[2][2])+"|"+str(rubiks[2][3])+"|"+ str(rubiks[1][2])+"|"+str(rubiks[1][3])+"|"+str(rubiks[4][2])+"|"+str(rubiks[4][3])+"|"+str(rubiks[3][2])+"|"+str(rubiks[3][3])+"|\n")
    myfile.write("    |"+ str(rubiks[5][0])+"|"+str(rubiks[5][1])+"|\n")
    myfile.write("    |"+ str(rubiks[5][2])+"|"+str(rubiks[5][3])+"|\n")
    return

#input: -myfile: name of the file where to write the moves 
#       -moves: list of moves
def print_moves(myfile, moves): 
    for move in moves:
        myfile.write(move+'\n')
    return

#output: number of clauses in the sat encoding 
def nb_constraints():
    nb_constraints = 11013
    return nb_constraints

#input: -myfile: name of file where to write constraints
#       -rubiks: initial state of the Rubik's cube to solve     
def constraints(myfile, rubiks):

    def output(s):
        myfile.write(s)

#   i,j,k,l: face i(1->6), facelet j(1->4), state k(11->22), color bit l(1->3)
    def newlitcol(i,j,k,l):
        output(str(i)+str(j)+str(k)+str(l)+" ")

#   k: state k(11->22)
    def newlitsta(k):
        output(str(650)+str(k)+" ")

#   s,m: step s(11->21), move m(0->3 for the exact move)(4->5 for the kind of move)
    def newlitmov(s,m):
        output(str(70)+str(s)+str(m)+" ")

#   i,j,k,c: face i(1->6), facelet j(1->4), state k(11->22), color c(0->5)
    def newcol(i,j,k,c):
        if (c<4):
            output("-")
        newlitcol(i,j,k,1)
        newcl()
        if (c<2 or c>3):
            output("-")
        newlitcol(i,j,k,2)
        newcl()
        if (c == 0 or c == 2 or c == 4):
            output("-")
        newlitcol(i,j,k,3)
        newcl()

    def newcl():
        output("0\n")

    def newcomment(s):
        output("c %s\n"%s)
    
    #initial state (72 clauses)
    for i in range(6):
        for j in range(4):   
            newcol(i+1,j+1,11,int(rubiks[i][j]))
             
    #at least one solved state (1 clause)
    for k in range(11,23):
        newlitsta(k)
    newcl()

    #at most one solved state (66 clauses)
    for k in range(11,22):
        for k1 in range(k+1,23):
            output("-")
            newlitsta(k)
            output("-")
            newlitsta(k1)
            newcl()

    #definition of solved state (1296 clauses)
    for k in range(11,23):
        for i in range(1,7):
            for j in range(1,4):
                for l in range(1,4):
                    output("-")
                    newlitsta(k)
                    newlitcol(i,j,k,l)
                    output("-")
                    newlitcol(i,4,k,l)
                    newcl()
                    output("-")
                    newlitsta(k)
                    output("-")
                    newlitcol(i,j,k,l)
                    newlitcol(i,4,k,l)
                    newcl()

    #move and type of move chosen must exist (44 clauses)
    for s in range(11,22):
        output("-")
        newlitmov(s,4)
        output("-")
        newlitmov(s,5)
        newcl()
        output("-")
        newlitmov(s,0)
        output("-")
        newlitmov(s,1)
        newcl()
        output("-")
        newlitmov(s,0)
        output("-")
        newlitmov(s,2)
        newcl()
        output("-")
        newlitmov(s,0)
        output("-")
        newlitmov(s,3)
        newcl()

    #state after a move (9504 clauses)
    for t in range(11,22):
        for l in range(1,4):
            for j in range(1,5):
                # facelets that do not move wrt the type of move (2376 clauses)
                newlitmov(t,4)
                newlitmov(t,5)
                output("-")
                newlitcol(6,j,t,l)
                newlitcol(6,j,t+1,l)
                newcl()
                newlitmov(t,4)
                newlitmov(t,5)
                output("-")
                newlitcol(6,j,t+1,l)
                newlitcol(6,j,t,l)
                newcl()

                newlitmov(t,4)
                output("-")
                newlitmov(t,5)
                output("-")
                newlitcol(5,j,t,l)
                newlitcol(5,j,t+1,l)
                newcl()
                newlitmov(t,4)
                output("-")
                newlitmov(t,5)
                output("-")
                newlitcol(5,j,t+1,l)
                newlitcol(5,j,t,l)
                newcl()

                output("-")
                newlitmov(t,4)
                newlitmov(t,5)
                output("-")
                newlitcol(4,j,t,l)
                newlitcol(4,j,t+1,l)
                newcl()
                output("-")
                newlitmov(t,4)
                newlitmov(t,5)
                output("-")
                newlitcol(4,j,t+1,l)
                newlitcol(4,j,t,l)
                newcl()

            for i in range(2,6):
                for j in range(3,5):
                    newlitmov(t,4)
                    newlitmov(t,5)
                    output("-")
                    newlitcol(i,j,t,l)
                    newlitcol(i,j,t+1,l)
                    newcl()
                    newlitmov(t,4)
                    newlitmov(t,5)
                    output("-")
                    newlitcol(i,j,t+1,l)
                    newlitcol(i,j,t,l)
                    newcl()

            for i in [1,2,6]:
                for j in [2,4]:
                    newlitmov(t,4)
                    output("-")
                    newlitmov(t,5)
                    output("-")
                    newlitcol(i,j,t,l)
                    newlitcol(i,j,t+1,l)
                    newcl()
                    newlitmov(t,4)
                    output("-")
                    newlitmov(t,5)
                    output("-")
                    newlitcol(i,j,t+1,l)
                    newlitcol(i,j,t,l)
                    newcl()

            for j in [1,3]:
                newlitmov(t,4)
                output("-")
                newlitmov(t,5)
                output("-")
                newlitcol(4,j,t,l)
                newlitcol(4,j,t+1,l)
                newcl()
                newlitmov(t,4)
                output("-")
                newlitmov(t,5)
                output("-")
                newlitcol(4,j,t+1,l)
                newlitcol(4,j,t,l)
                newcl()

            for j in range(1,3):
                output("-")
                newlitmov(t,4)
                newlitmov(t,5)
                output("-")
                newlitcol(1,j,t,l)
                newlitcol(1,j,t+1,l)
                newcl()
                output("-")
                newlitmov(t,4)
                newlitmov(t,5)
                output("-")
                newlitcol(1,j,t+1,l)
                newlitcol(1,j,t,l)
                newcl()

                output("-")
                newlitmov(t,4)
                newlitmov(t,5)
                output("-")
                newlitcol(3,2**j-1,t,l)
                newlitcol(3,2**j-1,t+1,l)
                newcl()
                output("-")
                newlitmov(t,4)
                newlitmov(t,5)
                output("-")
                newlitcol(3,2**j-1,t+1,l)
                newlitcol(3,2**j-1,t,l)
                newcl()

                output("-")
                newlitmov(t,4)
                newlitmov(t,5)
                output("-")
                newlitcol(5,j*2,t,l)
                newlitcol(5,j*2,t+1,l)
                newcl()
                output("-")
                newlitmov(t,4)
                newlitmov(t,5)
                output("-")
                newlitcol(5,j*2,t+1,l)
                newlitcol(5,j*2,t,l)
                newcl()

                output("-")
                newlitmov(t,4)
                newlitmov(t,5)
                output("-")
                newlitcol(6,j+2,t,l)
                newlitcol(6,j+2,t+1,l)
                newcl()
                output("-")
                newlitmov(t,4)
                newlitmov(t,5)
                output("-")
                newlitcol(6,j+2,t+1,l)
                newlitcol(6,j+2,t,l)
                newcl()

            #facelets that move wrt to the exact move (7128 clauses)     
            clockwise_order = [1, 2, 4, 3]
            counterclockwise_order = [1, 3, 4, 2]

            #move U
            side_u_clockwise = [2, 3, 4, 5]
            for i in range(0,4):
                for j in range(1,3):
                    newlitmov(t,0)
                    newlitmov(t,1)
                    newlitmov(t,2)
                    newlitmov(t,3)
                    output("-")
                    newlitcol(side_u_clockwise[i],j,t,l)
                    newlitcol(side_u_clockwise[(i+1)%4],j,t+1,l)
                    newcl()
                    newlitmov(t,0)
                    newlitmov(t,1)
                    newlitmov(t,2)
                    newlitmov(t,3)
                    output("-")
                    newlitcol(side_u_clockwise[(i+1)%4],j,t+1,l)
                    newlitcol(side_u_clockwise[i],j,t,l)
                    newcl()

                newlitmov(t,0)
                newlitmov(t,1)
                newlitmov(t,2)
                newlitmov(t,3)
                output("-")
                newlitcol(1,clockwise_order[i],t,l)
                newlitcol(1,clockwise_order[(i+1)%4],t+1,l)
                newcl()
                newlitmov(t,0)
                newlitmov(t,1)
                newlitmov(t,2)
                newlitmov(t,3)
                output("-")
                newlitcol(1,clockwise_order[(i+1)%4],t+1,l)
                newlitcol(1,clockwise_order[i],t,l)
                newcl()
                   
            #move U2
            for j in range(1,3):
                for i in range(2,6):
                    newlitmov(t,0)
                    newlitmov(t,1)
                    newlitmov(t,2)
                    output("-")
                    newlitmov(t,3)
                    output("-")
                    newlitcol(i,j,t,l)
                    newlitcol(i%4+2,j,t+1,l)
                    newcl()
                    newlitmov(t,0)
                    newlitmov(t,1)
                    newlitmov(t,2)
                    output("-")
                    newlitmov(t,3)
                    output("-")
                    newlitcol(i%4+2,j,t+1,l)
                    newlitcol(i,j,t,l)
                    newcl()

            newlitmov(t,0)
            newlitmov(t,1)
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(1,1,t,l)
            newlitcol(1,4,t+1,l)
            newcl()
            newlitmov(t,0)
            newlitmov(t,1)
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(1,1,t,l)
            output("-")
            newlitcol(1,4,t+1,l)
            newcl()

            newlitmov(t,0)
            newlitmov(t,1)
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(1,2,t,l)
            newlitcol(1,3,t+1,l)
            newcl()
            newlitmov(t,0)
            newlitmov(t,1)
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(1,2,t,l)
            output("-")
            newlitcol(1,3,t+1,l)
            newcl()

            newlitmov(t,0)
            newlitmov(t,1)
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(1,4,t,l)
            newlitcol(1,1,t+1,l)
            newcl()
            newlitmov(t,0)
            newlitmov(t,1)
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(1,4,t,l)
            output("-")
            newlitcol(1,1,t+1,l)
            newcl()

            newlitmov(t,0)
            newlitmov(t,1)
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(1,3,t,l)
            newlitcol(1,2,t+1,l)
            newcl()
            newlitmov(t,0)
            newlitmov(t,1)
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(1,3,t,l)
            output("-")
            newlitcol(1,2,t+1,l)
            newcl()

            #move U*
            side_u_counterclockwise = [2, 5, 4, 3]
            for i in range(0,4):
                for j in range(1,3):
                    newlitmov(t,0)
                    newlitmov(t,1)
                    output("-")
                    newlitmov(t,2)
                    newlitmov(t,3)
                    output("-")
                    newlitcol(side_u_counterclockwise[i],j,t,l)
                    newlitcol(side_u_counterclockwise[(i+1)%4],j,t+1,l)
                    newcl()
                    newlitmov(t,0)
                    newlitmov(t,1)
                    output("-")
                    newlitmov(t,2)
                    newlitmov(t,3)
                    output("-")
                    newlitcol(side_u_counterclockwise[(i+1)%4],j,t+1,l)
                    newlitcol(side_u_counterclockwise[i],j,t,l)
                    newcl()

                newlitmov(t,0)
                newlitmov(t,1)
                output("-")
                newlitmov(t,2)
                newlitmov(t,3)
                output("-")
                newlitcol(1,counterclockwise_order[i],t,l)
                newlitcol(1,counterclockwise_order[(i+1)%4],t+1,l)
                newcl()
                newlitmov(t,0)
                newlitmov(t,1)
                output("-")
                newlitmov(t,2)
                newlitmov(t,3)
                output("-")
                newlitcol(1,counterclockwise_order[(i+1)%4],t+1,l)
                newlitcol(1,counterclockwise_order[i],t,l)
                newcl()

            #move L
            l_side_move_clock = [1,2,6]
            for j in [1,3]:
                for i in range(0,2):
                    newlitmov(t,0)
                    newlitmov(t,1)
                    output("-")
                    newlitmov(t,2)
                    output("-")
                    newlitmov(t,3)
                    output("-")
                    newlitcol(l_side_move_clock[i],j,t,l)
                    newlitcol(l_side_move_clock[i+1],j,t+1,l)
                    newcl()
                    newlitmov(t,0)
                    newlitmov(t,1)
                    output("-")
                    newlitmov(t,2)
                    output("-")
                    newlitmov(t,3)
                    newlitcol(l_side_move_clock[i],j,t,l)
                    output("-")
                    newlitcol(l_side_move_clock[i+1],j,t+1,l)
                    newcl()

            newlitmov(t,0)
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(6,1,t,l)
            newlitcol(4,4,t+1,l)
            newcl()
            newlitmov(t,0)
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(6,1,t,l)
            output("-")
            newlitcol(4,4,t+1,l)
            newcl()

            newlitmov(t,0)
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(6,3,t,l)
            newlitcol(4,2,t+1,l)
            newcl()
            newlitmov(t,0)
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(6,3,t,l)
            output("-")
            newlitcol(4,2,t+1,l)
            newcl()

            newlitmov(t,0)
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(4,4,t,l)
            newlitcol(1,1,t+1,l)
            newcl()
            newlitmov(t,0)
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(4,4,t,l)
            output("-")
            newlitcol(1,1,t+1,l)
            newcl()

            newlitmov(t,0)
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(4,2,t,l)
            newlitcol(1,3,t+1,l)
            newcl()
            newlitmov(t,0)
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(4,2,t,l)
            output("-")
            newlitcol(1,3,t+1,l)
            newcl()

            for i in range(0,4):
                newlitmov(t,0)
                newlitmov(t,1)
                output("-")
                newlitmov(t,2)
                output("-")
                newlitmov(t,3)
                output("-")
                newlitcol(3,clockwise_order[i],t,l)
                newlitcol(3,clockwise_order[(i+1)%4],t+1,l)
                newcl()
                newlitmov(t,0)
                newlitmov(t,1)
                output("-")
                newlitmov(t,2)
                output("-")
                newlitmov(t,3)
                output("-")
                newlitcol(3,clockwise_order[(i+1)%4],t+1,l)
                newlitcol(3,clockwise_order[i],t,l)
                newcl()

            #move L2
            for j in [1,3]:
                newlitmov(t,0)
                output("-")    
                newlitmov(t,1)
                newlitmov(t,2)
                newlitmov(t,3)
                output("-")
                newlitcol(1,j,t,l)
                newlitcol(6,j,t+1,l)
                newcl()
                newlitmov(t,0)
                output("-")    
                newlitmov(t,1)
                newlitmov(t,2)
                newlitmov(t,3)
                newlitcol(1,j,t,l)
                output("-")
                newlitcol(6,j,t+1,l)
                newcl()

                newlitmov(t,0)
                output("-")    
                newlitmov(t,1)
                newlitmov(t,2)
                newlitmov(t,3)
                output("-")
                newlitcol(6,j,t,l)
                newlitcol(1,j,t+1,l)
                newcl()
                newlitmov(t,0)
                output("-")    
                newlitmov(t,1)
                newlitmov(t,2)
                newlitmov(t,3)
                newlitcol(6,j,t,l)
                output("-")
                newlitcol(1,j,t+1,l)
                newcl()

            newlitmov(t,0)
            output("-")    
            newlitmov(t,1)
            newlitmov(t,2)
            newlitmov(t,3)
            output("-")
            newlitcol(2,1,t,l)
            newlitcol(4,4,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")    
            newlitmov(t,1)
            newlitmov(t,2)
            newlitmov(t,3)
            newlitcol(2,1,t,l)
            output("-")
            newlitcol(4,4,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")    
            newlitmov(t,1)
            newlitmov(t,2)
            newlitmov(t,3)
            output("-")
            newlitcol(2,3,t,l)
            newlitcol(4,2,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")    
            newlitmov(t,1)
            newlitmov(t,2)
            newlitmov(t,3)
            newlitcol(2,3,t,l)
            output("-")
            newlitcol(4,2,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")    
            newlitmov(t,1)
            newlitmov(t,2)
            newlitmov(t,3)
            output("-")
            newlitcol(4,4,t,l)
            newlitcol(2,1,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")    
            newlitmov(t,1)
            newlitmov(t,2)
            newlitmov(t,3)
            newlitcol(4,4,t,l)
            output("-")
            newlitcol(2,1,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")    
            newlitmov(t,1)
            newlitmov(t,2)
            newlitmov(t,3)
            output("-")
            newlitcol(4,2,t,l)
            newlitcol(2,3,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")    
            newlitmov(t,1)
            newlitmov(t,2)
            newlitmov(t,3)
            newlitcol(4,2,t,l)
            output("-")
            newlitcol(2,3,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            newlitmov(t,2)
            newlitmov(t,3)
            output("-")
            newlitcol(3,1,t,l)
            newlitcol(3,4,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            newlitmov(t,2)
            newlitmov(t,3)
            newlitcol(3,1,t,l)
            output("-")
            newlitcol(3,4,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            newlitmov(t,2)
            newlitmov(t,3)
            output("-")
            newlitcol(3,2,t,l)
            newlitcol(3,3,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            newlitmov(t,2)
            newlitmov(t,3)
            newlitcol(3,2,t,l)
            output("-")
            newlitcol(3,3,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            newlitmov(t,2)
            newlitmov(t,3)
            output("-")
            newlitcol(3,4,t,l)
            newlitcol(3,1,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            newlitmov(t,2)
            newlitmov(t,3)
            newlitcol(3,4,t,l)
            output("-")
            newlitcol(3,1,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            newlitmov(t,2)
            newlitmov(t,3)
            output("-")
            newlitcol(3,3,t,l)
            newlitcol(3,2,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            newlitmov(t,2)
            newlitmov(t,3)
            newlitcol(3,3,t,l)
            output("-")
            newlitcol(3,2,t+1,l)
            newcl()

            #move L*
            l_side_move_counterclock = [6,2,1]
            for j in [1,3]:
                for i in range(0,2):
                    newlitmov(t,0)
                    output("-")
                    newlitmov(t,1)
                    newlitmov(t,2)
                    output("-")
                    newlitmov(t,3)
                    output("-")
                    newlitcol(l_side_move_counterclock[i],j,t,l)
                    newlitcol(l_side_move_counterclock[i+1],j,t+1,l)
                    newcl()
                    newlitmov(t,0)
                    output("-")
                    newlitmov(t,1)
                    newlitmov(t,2)
                    output("-")
                    newlitmov(t,3)
                    newlitcol(l_side_move_counterclock[i],j,t,l)
                    output("-")
                    newlitcol(l_side_move_counterclock[i+1],j,t+1,l)
                    newcl()

            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(1,1,t,l)
            newlitcol(4,4,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(1,1,t,l)
            output("-")
            newlitcol(4,4,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(1,3,t,l)
            newlitcol(4,2,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(1,3,t,l)
            output("-")
            newlitcol(4,2,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(4,4,t,l)
            newlitcol(6,1,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(4,4,t,l)
            output("-")
            newlitcol(6,1,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(4,2,t,l)
            newlitcol(6,3,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(4,2,t,l)
            output("-")
            newlitcol(6,3,t+1,l)
            newcl()

            for i in range(0,4):
                newlitmov(t,0)
                output("-")
                newlitmov(t,1)
                newlitmov(t,2)
                output("-")
                newlitmov(t,3)
                output("-")
                newlitcol(3,counterclockwise_order[i],t,l)
                newlitcol(3,counterclockwise_order[(i+1)%4],t+1,l)
                newcl()
                newlitmov(t,0)
                output("-")
                newlitmov(t,1)
                newlitmov(t,2)
                output("-")
                newlitmov(t,3)
                output("-")
                newlitcol(3,counterclockwise_order[(i+1)%4],t+1,l)
                newlitcol(3,counterclockwise_order[i],t,l)
                newcl()

            #move F
            side_f_clockwise = [1, 5, 6, 3]
            facelet_left_side_clockwise = [3, 1, 2, 4]
            facelet_right_side_clockwise = [4, 3, 1, 2]

            for i in range(0,4):
                newlitmov(t,0)
                output("-")
                newlitmov(t,1)
                output("-")
                newlitmov(t,2)
                newlitmov(t,3)
                output("-")
                newlitcol(side_f_clockwise[i],facelet_left_side_clockwise[i],t,l)
                newlitcol(side_f_clockwise[(i+1)%4],facelet_left_side_clockwise[(i+1)%4],t+1,l)
                newcl()
                newlitmov(t,0)
                output("-")
                newlitmov(t,1)
                output("-")
                newlitmov(t,2)
                newlitmov(t,3)
                output("-")
                newlitcol(side_f_clockwise[(i+1)%4],facelet_left_side_clockwise[(i+1)%4],t+1,l)
                newlitcol(side_f_clockwise[i],facelet_left_side_clockwise[i],t,l)
                newcl()

                newlitmov(t,0)
                output("-")
                newlitmov(t,1)
                output("-")
                newlitmov(t,2)
                newlitmov(t,3)
                output("-")
                newlitcol(side_f_clockwise[i],facelet_right_side_clockwise[i],t,l)
                newlitcol(side_f_clockwise[(i+1)%4],facelet_right_side_clockwise[(i+1)%4],t+1,l)
                newcl()
                newlitmov(t,0)
                output("-")
                newlitmov(t,1)
                output("-")
                newlitmov(t,2)
                newlitmov(t,3)
                output("-")
                newlitcol(side_f_clockwise[(i+1)%4],facelet_right_side_clockwise[(i+1)%4],t+1,l)
                newlitcol(side_f_clockwise[i],facelet_right_side_clockwise[i],t,l)
                newcl()

                newlitmov(t,0)
                output("-")
                newlitmov(t,1)
                output("-")
                newlitmov(t,2)
                newlitmov(t,3)
                output("-")
                newlitcol(2,clockwise_order[i],t,l)
                newlitcol(2,clockwise_order[(i+1)%4],t+1,l)
                newcl()
                newlitmov(t,0)
                output("-")
                newlitmov(t,1)
                output("-")
                newlitmov(t,2)
                newlitmov(t,3)
                output("-")
                newlitcol(2,clockwise_order[(i+1)%4],t+1,l)
                newlitcol(2,clockwise_order[i],t,l)
                newcl()
            
            #move F2
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(1,3,t,l)
            newlitcol(6,2,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(1,3,t,l)
            output("-")
            newlitcol(6,2,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(6,2,t,l)
            newlitcol(1,3,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(6,2,t,l)
            output("-")
            newlitcol(1,3,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(1,4,t,l)
            newlitcol(6,1,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(1,4,t,l)
            output("-")
            newlitcol(6,1,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(6,1,t,l)
            newlitcol(1,4,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(6,1,t,l)
            output("-")
            newlitcol(1,4,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(3,2,t,l)
            newlitcol(5,3,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(3,2,t,l)
            output("-")
            newlitcol(5,3,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(3,4,t,l)
            newlitcol(5,1,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(3,4,t,l)
            output("-")
            newlitcol(5,1,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(5,1,t,l)
            newlitcol(3,4,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(5,1,t,l)
            output("-")
            newlitcol(3,4,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(5,3,t,l)
            newlitcol(3,2,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(5,3,t,l)
            output("-")
            newlitcol(3,2,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(2,1,t,l)
            newlitcol(2,4,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(2,1,t,l)
            output("-")
            newlitcol(2,4,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(2,2,t,l)
            newlitcol(2,3,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(2,2,t,l)
            output("-")
            newlitcol(2,3,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(2,4,t,l)
            newlitcol(2,1,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(2,4,t,l)
            output("-")
            newlitcol(2,1,t+1,l)
            newcl()

            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            output("-")
            newlitcol(2,3,t,l)
            newlitcol(2,2,t+1,l)
            newcl()
            newlitmov(t,0)
            output("-")
            newlitmov(t,1)
            output("-")
            newlitmov(t,2)
            output("-")
            newlitmov(t,3)
            newlitcol(2,3,t,l)
            output("-")
            newlitcol(2,2,t+1,l)
            newcl()

            #move F*
            side_f_counterclockwise = [1, 3, 6, 5]
            facelet_left_side_counterclockwise = [3, 4, 2, 1]
            facelet_right_side_counterclockwise = [4, 2, 1, 3]

            for i in range(0,4):
                output("-")
                newlitmov(t,0)
                newlitmov(t,1)
                newlitmov(t,2)
                newlitmov(t,3)
                output("-")
                newlitcol(side_f_counterclockwise[i],facelet_left_side_counterclockwise[i],t,l)
                newlitcol(side_f_counterclockwise[(i+1)%4],facelet_left_side_counterclockwise[(i+1)%4],t+1,l)
                newcl()
                output("-")
                newlitmov(t,0)
                newlitmov(t,1)
                newlitmov(t,2)
                newlitmov(t,3)
                output("-")
                newlitcol(side_f_counterclockwise[(i+1)%4],facelet_left_side_counterclockwise[(i+1)%4],t+1,l)
                newlitcol(side_f_counterclockwise[i],facelet_left_side_counterclockwise[i],t,l)
                newcl()

                output("-")
                newlitmov(t,0)
                newlitmov(t,1)
                newlitmov(t,2)
                newlitmov(t,3)
                output("-")
                newlitcol(side_f_counterclockwise[i],facelet_right_side_counterclockwise[i],t,l)
                newlitcol(side_f_counterclockwise[(i+1)%4],facelet_right_side_counterclockwise[(i+1)%4],t+1,l)
                newcl()
                output("-")
                newlitmov(t,0)
                newlitmov(t,1)
                newlitmov(t,2)
                newlitmov(t,3)
                output("-")
                newlitcol(side_f_counterclockwise[(i+1)%4],facelet_right_side_counterclockwise[(i+1)%4],t+1,l)
                newlitcol(side_f_counterclockwise[i],facelet_right_side_counterclockwise[i],t,l)
                newcl()

                output("-")
                newlitmov(t,0)
                newlitmov(t,1)
                newlitmov(t,2)
                newlitmov(t,3)
                output("-")
                newlitcol(2,counterclockwise_order[i],t,l)
                newlitcol(2,counterclockwise_order[(i+1)%4],t+1,l)
                newcl()
                output("-")
                newlitmov(t,0)
                newlitmov(t,1)
                newlitmov(t,2)
                newlitmov(t,3)
                output("-")
                newlitcol(2,counterclockwise_order[(i+1)%4],t+1,l)
                newlitcol(2,counterclockwise_order[i],t,l)
                newcl()

    #not twice the same kind of move in a row (30 clauses)
    for t in range(11,21):
        newlitmov(t,4)
        newlitmov(t,5)
        newlitmov(t+1,4)
        newlitmov(t+1,5)
        newcl()

        newlitmov(t,4)
        output("-")
        newlitmov(t,5)
        newlitmov(t+1,4)
        output("-")
        newlitmov(t+1,5)
        newcl()

        output("-")
        newlitmov(t,4)
        newlitmov(t,5)
        output("-")
        newlitmov(t+1,4)
        newlitmov(t+1,5)
        newcl()

#input: -filename: name of cnf file
#       -phase: selection strategy (string)
#output: -moves: list with moves to solve the Rubik's cube
#        -time: wall clock time in second for the sat solver
def rubiks_solve(filename, phase):
    if phase == "":
        command = "java -jar sat4j-sat.jar "+ filename
    else:
        command = "java -jar sat4j-sat.jar -S PHASE=" + phase +"LiteralSelectionStrategy "+ filename  
    process = subprocess.Popen(command, shell=True,
                               stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    out, err = process.communicate()
    
    out_split = out.split(b'\r\n')
    out_split.pop()
    time = out_split.pop()
    time = time.split(b' ').pop()
    time = time.decode("utf-8")

    table = [0 for i in range(9)]
    table[0] = 'U'
    table[1] = 'U2'
    table[2] = 'U*'
    table[3] = 'L'
    table[4] = 'L2'
    table[5] = 'L*'
    table[6] = 'F'
    table[7] = 'F2'
    table[8] = 'F*'
    for line in out.split(b'\n'):
        line = line.decode("utf-8")
        if line == "" or line[0] == 'c':
            continue
        line = line.strip()
        if line[0] == 's':
            if line != 's SATISFIABLE':
                print("unsatisfiable")
                return [],time
            continue
        if line[0] == 'v':
            line = line[2:]
            units = line.split()
            if units.pop() != '0':
                exit("strange output from SAT solver:" + line + "\n")
            units = [int(x) for x in units if int(x) >= 0]

            final_state = 0
            for number in units:
                if (number//1000) == 65:
                    final_state = (number%100)-11
                    print("number of moves: " + str(final_state))

            moves = [0 for i in range(final_state)]
            for number in units:
                action = (number//10)%100-10
                if (number//1000) == 70 and action <= final_state and (number%10) <= 3:
                    moves[action-1] += 2**(3-(number%10))

            for i in range(final_state):
                moves[i] = table[moves[i]]

            return moves,time
            
        exit("strange output from SAT solver:" + line + "\n")
        return [],time


# start of the main code
# first arg: name of the file that contains the Rubik's cube to solve
# second arg: selection strategy (Positive or Negative), nothing if default strategy
if len(sys.argv) < 2:
    exit("argument missing: filename")

rubiks = read_file(str(sys.argv[1]))
print_rubiks(sys.stdout, rubiks)

myfile = open("rubiks.cnf", 'w')
myfile.write("p cnf "+str(70215)+" "+str(nb_constraints())+"\n")
constraints(myfile, rubiks)
myfile.close()

if len(sys.argv) == 2:
    phase = ""
else:
    phase = sys.argv[2]

moves, time = rubiks_solve("rubiks.cnf", phase)
print_moves(sys.stdout, moves)
print("Solution found in " + time + " seconds")
